"""empty message

Revision ID: 6efd41ac4306
Revises: 44d030632caf
Create Date: 2021-01-14 23:18:08.868115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efd41ac4306'
down_revision = '44d030632caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encrypted_note', sa.Column('salt', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encrypted_note', 'salt')
    # ### end Alembic commands ###
